language: python

matrix:
  include:

    - os: linux
      python: 3.6
      name: ubuntu 20.04 - python@3.6
      dist: focal
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.7
      name: ubuntu 20.04 - python@3.7
      dist: focal
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.8
      name: ubuntu 20.04 - python@3.8
      dist: focal
      sudo: true
      env:
        - MATRIX_EVAL=""

    - os: linux
      python: 3.9
      name: ubuntu 20.04 - python@3.8
      dist: focal
      sudo: true
      env:
        - MATRIX_EVAL=""

before_install:
  - travis_retry eval "${MATRIX_EVAL}"

    # check python installation and upgrade pip
  - python -m pip install --upgrade pip
  - python -m pip --version
    # install dependencies
  - python -m pip install requirements.txt

  # testing libraries
  - python -m pip install pytest==3.0.7
  - python -m pip install hypothesis>=4.13.0
  - python -m pip install codecov
  - python -m pip install pytest-cov

install:
  - python setup.py develop --user

script:
  - travis_wait 45 python -m pytest --cov=3DFemNet --cov-config=.coveragerc

after_succes:
  - codecov
